// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import react from '@astrojs/react';
import { existsSync, readFileSync } from 'node:fs';

// specs.json is generated by `sysspec docs data` (task docs:generate).
const dataFile = new URL('./src/data/specs.json', import.meta.url);
const specs = existsSync(dataFile)
  ? JSON.parse(readFileSync(dataFile, 'utf8'))
  : { services: [], edges: [], unconsumed: [] };

// Reading order: contract → events → data → acceptance criteria → context → changelog.
const servicePages = (s) => {
  const byKind = (kind) => s.artifacts.filter((a) => a.kind === kind);
  const pages = [{ label: 'Overview', link: `/services/${s.name}/` }];
  for (const a of byKind('openapi'))
    pages.push({ label: 'API Contract (OpenAPI)', link: `/services/${s.name}/${a.stem}/` });
  for (const a of byKind('asyncapi'))
    pages.push({ label: 'Events (AsyncAPI)', link: `/services/${s.name}/${a.stem}/` });
  const contracts = byKind('data-contract');
  for (const a of contracts)
    pages.push({
      label: contracts.length > 1 ? `Data: ${a.odcs.name ?? a.stem}` : 'Data (Data Contracts)',
      link: `/services/${s.name}/${a.stem}/`,
    });
  if (byKind('feature').length)
    pages.push({ label: 'Acceptance criteria', link: `/services/${s.name}/features/` });
  for (const a of byKind('doc'))
    pages.push({ label: a.label ?? a.summary ?? a.stem, link: `/services/${s.name}/${a.stem}/` });
  if (s.changelog.length)
    pages.push({ label: 'Changelog', link: `/services/${s.name}/changelog/` });
  return pages;
};

// On GitHub Pages the site lives under /<repo>; locally at /.
const repo = process.env.GITHUB_REPOSITORY;

export default defineConfig({
  site: repo ? `https://${repo.split('/')[0]}.github.io` : undefined,
  base: repo ? `/${repo.split('/')[1]}` : '/',
  // Relative paths resolve against the config's physical location, which
  // breaks when docs-site is reached through a symlink - the kit repo
  // overrides with an absolute path.
  outDir: process.env.DOCS_SITE_OUT ?? '../site',
  integrations: [
    react(),
    starlight({
      title: 'System specs',
      pagefind: true,
      customCss: ['./src/styles/specs.css'],
      sidebar: [
        { label: 'Overview', link: '/' },
        { label: 'Drive an implementation', link: '/implementing/' },
        { label: 'Build a consumer', link: '/consuming/' },
        ...specs.services.map((s) => ({
          label: s.title,
          items: servicePages(s),
        })),
      ],
    }),
  ],
});
